import { pgTable, serial, text, timestamp, uuid, boolean, date, time, inet } from 'drizzle-orm/pg-core';

export const customers = pgTable('customers', {
  id: serial('id').primaryKey(),
  userId: uuid('user_id').notNull(),
  name: text('name').notNull(),
  phone: text('phone').notNull(),
  email: text('email').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  
  addedBy: uuid('added_by'),
  firstname: text('firstname'),
  lastname: text('lastname'),
  phone2: text('phone2'),
  email2: text('email2'),
  country: text('country'),
  city: text('city'),
  address: text('address'),
  pBox: text('p_box'),
  status: text('status'),
  assignedTo: uuid('assigned_to'),
  sex: text('sex'),
  source: text('source'),
  campaign: text('campaign'),
  param1: text('param1'),
  param2: text('param2'),
  param3: text('param3'),
  param4: text('param4'),
  ip: inet('ip'),
  date: date('date'),
  time: time('time'),
  lastMDate: timestamp('last_m_date'),
  groupName: text('group_name'),
  clientId: uuid('client_id'),
  isRemoved: boolean('is_removed').default(false),
  createMethod: text('create_method'),
  statusEditDate: timestamp('status_edit_date'),
  color: text('color'),
  statusName: text('statusName'),
  sourceName: text('sourceName'),
  campaignName: text('campaignName'),
  groupName: text('groupName'),
});